# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c9befe41d76934c96c5ab1c790d9da2973351fb58e80b2fd57d05084fe550204fc38d49417b6399d10ba093de954bd5c722e3b0691720275c24bd9d4019522

test:
  secret_key_base: 185cadb098519560884176d94872279ccc5c639d5231089a8e55ebbc78c89719dfe5c29ff2b2cfca714ff000746b95779a93edad134927552316e32bc257a30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
